version: "3.9"

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cli
    # Mount the local 'downloads' directory to '/home/cliuser/downloads' inside the container
    # This allows files downloaded in the container to persist on the host machine
    # and enables sharing files between the host and container
    volumes:
      - ~/Documents/programing/42/projects/:/home/cliuser/downloads
    tty: true
    stdin_open: true
    command: /bin/bash

  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notebook
    volumes:
      - ~/Documents/programing/42/projects/ft_matrix:/home/cliuser/downloads/ft_matrix
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --no-browser
